Name: onPushToMainDeploymentWorkflow
SchemaVersion: "1.0"
Triggers:
  - Type: PUSH
    Branches:
      - main
Actions:
  BackendCDKBootstrapAction:
    Identifier: aws/cdk-bootstrap@v1
    Compute:
      Type: Lambda
    Inputs:
      Sources:
        - WorkflowSource
    Configuration:
      Region: eu-central-1
    Environment:
      Name: default_environment
      Connections:
        - Name: ProductShared
          Role: CodeCatalystWorkflowDevelopmentRole-cc-workshop-jm
  BackendCDKDeploy:
    Identifier: aws/cdk-deploy@v1
    Compute:
      Type: EC2
    Inputs:
      Sources:
        - WorkflowSource
    DependsOn:
      - BackendCDKBootstrapAction
    Configuration:
      StackName: TodoAppBackendStack-py14y
      Region: eu-central-1
      Context: '{"stack_name": "TodoAppBackendStack-py14y"}'
    Environment:
      Name: default_environment
      Connections:
        - Name: ProductShared
          Role: CodeCatalystWorkflowDevelopmentRole-cc-workshop-jm
